Repository ucsb-cs156-w24/proj-happy-cows-w24-4pm-3, pull requests merged in 2024-03, with the labels that each got.

#13 Merge bug fix that disables buying negative # of cows
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/NegativeBuyNumberException.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10

#15 Add Entity and Repository File for Announcement backend (Issue B1)
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcement.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
Labels: 5

#18 fixed the className error
  frontend/src/main/pages/HomePage.js
Labels: 5

#19 Aa fix leader board
  frontend/src/main/components/OurTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 10

#29 bh - added showChat to CommonsTable
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
Labels: 10

#31 added fixtures, form, table, and storybook entries + tests for F1
  frontend/src/fixtures/announcementFixtures.js
  frontend/src/main/components/Announcement/AnnouncementForm.js
  frontend/src/main/components/Announcement/AnnouncementTable.js
  frontend/src/main/utils/announcementUtils.js
  frontend/src/stories/components/Announcement/AnnouncementForm.stories.js
  frontend/src/stories/components/Announcement/AnnouncementTable.stories.js
  frontend/src/tests/components/Announcement/AnnouncementsForm.test.js
  frontend/src/tests/components/Announcement/AnnouncementsTable.test.js
  frontend/src/tests/utils/announcementUtils.test.js
Labels: 20

#35 Add Controller and Tests for Announcement Issue B2
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcements.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 10
